services:
  rh-lifecycle-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: quay.io/jgoh/rhlifecyclesummary:latest
    container_name: rh-dashboard
    ports:
    - "8881:8881"
    restart: always
    volumes:
    - .:/app
    environment:
    - PYTHONUNBUFFERED=1
    - WATCHFILES_FORCE_POLLING=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8881/" ]
      interval: 30s
      timeout: 5s
      retries: 3
